import { test, expect } from '@playwright/test';

test('수익 분해·배당 분류·투자 논거 저장과 변경 이력을 실제 DB로 확인한다', async ({ page }) => {
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.goto('/login?return_to=/portfolio');
  await page.locator('#loginEmail').fill('browser@example.com');
  await page.locator('#loginPassword').fill('browser-test-password');
  await page.getByRole('button', { name: '이메일로 로그인' }).click();
  await expect(page).toHaveURL(/\/portfolio$/);
  await page.locator('.pf-tab[data-tab="performance"]').click();
  await page.locator('#pfAttributionStart').fill('2026-01-01');
  await page.getByRole('button', { name: '분해 조회' }).click();
  await expect(page.locator('#pfAttributionContent')).toContainText('+50,000원');
  await expect(page.locator('#pfAttributionContent')).toContainText('합계 검산 차이 0원');
  await page.locator('#pfAttributionWrap').getByText('실제 배당·비용 분류 기록', { exact: true }).click();
  const form = page.locator('#pfIncomeForm');
  await form.locator('[name="date"]').fill(new Date(Date.now()-86400000).toLocaleDateString('sv-SE', { timeZone: 'Asia/Seoul' }));
  await form.locator('[name="amount_krw"]').fill('1000');
  await form.locator('[name="memo"]').fill('실제 수령 배당');
  await form.getByRole('button', { name: '분류 기록' }).click();
  await expect(page.locator('#pfIncomeEvents')).toContainText('실제 수령 배당');
  await expect(page.locator('#pfAttributionContent')).toContainText('-1,000원');
  await page.locator('#pfThesisEditor summary').click();
  const thesis = page.locator('#pfThesisForm');
  await thesis.locator('[name="stock_code"]').fill('005930');
  await thesis.locator('[name="thesis"]').fill('영업이익률 회복을 기대하고 보유');
  await thesis.locator('[name="invalidation"]').fill('영업이익률 10% 미만이면 투자 가정 재검토');
  await thesis.locator('[name="metric"]').selectOption('operating_margin_pct');
  await thesis.locator('[name="threshold"]').fill('10');
  await thesis.getByRole('button', { name: '논거 저장' }).click();
  await expect(page.locator('#pfThesisContent')).toContainText('반증 조건 충족');
  await page.locator('#pfThesisContent').getByRole('button', { name: '변경 이력' }).click();
  await expect(page.locator('.pf-thesis-history')).toContainText('현재 9%');
  await page.reload();
  await page.locator('.pf-tab[data-tab="performance"]').click();
  await expect(page.locator('#pfThesisContent')).toContainText('영업이익률 회복을 기대하고 보유');
  await page.locator('#pfThesisContent').getByRole('button', { name: '보관', exact: true }).click();
  await expect(page.locator('#pfThesisContent')).toContainText('보관됨');
  await page.locator('#pfThesisContent').getByRole('button', { name: '추적 재개' }).click();
  await expect(page.locator('#pfThesisContent')).toContainText('반증 조건 충족');
  await page.locator('#pfAttributionWrap').screenshot({ path: 'test-results/attribution-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#pfSimpleToggle').click();
  await page.locator('.pf-tab[data-tab="performance"]').click();
  await expect(page.locator('#pfThesisContent')).toContainText('반증 조건 충족');
  await page.locator('#pfThesisWrap').scrollIntoViewIfNeeded();
  await page.locator('#pfThesisWrap').screenshot({ path: 'test-results/theses-mobile.png' });
  expect(await page.locator('#pfThesisWrap').evaluate(el => el.scrollWidth <= el.clientWidth+1)).toBe(true);
});
