import {test,expect} from '@playwright/test';

test('한국투자증권 미리보기 취소·연결·합산·동기화·해제와 휴대폰 화면', async ({page},testInfo)=>{
  await page.routeWebSocket('**/ws/namuh',()=>{});
  await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
  await page.goto('/login');
  await page.request.post('/api/auth/register',{data:{email:`kis-${Date.now()}@example.com`,name:'한국투자 검증',password:'browser-test-password'},headers:{Origin:'http://127.0.0.1:18765'}});
  await page.goto('/portfolio');
  await expect(page.locator('#pfAccountSelect option')).toHaveCount(2);
  await page.locator('#pfAccountsOpen').click();
  await page.locator('#pfAccountName').fill('한국투자 주식');
  await page.locator('#pfAccountCreate').click();
  const card=page.locator('#pfAccountsList .pf-account-card').filter({has:page.locator('h3',{hasText:'한국투자 주식'})});
  await expect(card).toBeVisible();
  const aid=await card.getAttribute('data-account');
  const openAndPreview=async()=>{
    await card.locator('[data-account-action="connect-kis"]').click();
    await page.locator('#pfNhKey').fill('kis-browser-'+testInfo.testId);
    await page.locator('#pfNhSecret').fill('test-kis-secret');
    await page.locator('#pfKisAccount').fill('12345678-01');
    await page.locator('#pfKisHts').fill('test_hts');
    await page.locator('#pfNhVerify').click();
    await expect(page.locator('#pfNhChoices')).toContainText('1234567801');
    await page.locator('#pfNhPreviewButton').click();
    await expect(page.locator('#pfNhSave')).toBeEnabled();
  };
  await openAndPreview();
  await page.locator('#pfNhClose').click();
  let account=(await (await page.request.get('/api/portfolio/accounts')).json()).find(row=>row.account_id===aid);
  expect(account.broker).toBeNull(); expect(account.holdings_count).toBe(0);
  await openAndPreview();
  await page.setViewportSize({width:390,height:844});
  await page.locator('#pfNhDialog').screenshot({path:testInfo.outputPath('kis-mobile.png')});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);
  await page.locator('#pfNhSave').click();
  await expect(page.locator('#pfNhDialog')).not.toBeVisible();
  await expect(card).toContainText('한국투자증권 1234567801');
  account=(await (await page.request.get('/api/portfolio/accounts')).json()).find(row=>row.account_id===aid);
  expect(account.broker).toBe('kis'); expect(account.holdings_count).toBe(2);
  expect(JSON.stringify(account)).not.toMatch(/test_hts|test-kis-secret|ciphertext/);
  await card.locator('[data-account-action="sync"]').click();
  await expect(page.locator('#pfAccountsStatus')).toContainText('반영했습니다');
  const before=await (await page.request.get('/api/portfolio?account_id='+aid)).json();
  expect(before.find(row=>row.stock_code==='CASH_KRW').quantity).toBe(5000);
  page.once('dialog',dialog=>dialog.accept());
  await card.locator('[data-account-action="disconnect"]').click();
  await expect(card.locator('[data-account-action="connect-kis"]')).toBeVisible();
  const after=await (await page.request.get('/api/portfolio?account_id='+aid)).json();
  expect(after).toEqual(before);
});
