import { test, expect } from '@playwright/test';

test('계좌별 등록·합산·매매 격리와 NH 미리보기 취소·연결을 실제 저장으로 확인한다', async ({ page }, testInfo) => {
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.goto('/login');
  const signup = await page.request.post('/api/auth/register', { data: {email: `accounts-${Date.now()}@example.com`, name: '계좌 검증', password: 'browser-test-password'}, headers: {Origin: 'http://127.0.0.1:18765'} });
  expect(signup.ok()).toBe(true);
  await page.goto('/portfolio');
  await expect(page.locator('#pfAccountSelect option')).toHaveCount(2);
  const api = (path, options) => page.evaluate(async ({path, options}) => {
    const response = await fetch(path, options);
    return {status: response.status, body: await response.json()};
  }, {path, options});
  const accounts = (await api('/api/portfolio/accounts')).body;
  const initial = accounts[0].account_id;
  await api('/api/portfolio/005930', {method:'PUT', headers:{'Content-Type':'application/json','X-Portfolio-Account':initial}, body:JSON.stringify({quantity:10,avg_price:70000,stock_name:'삼성전자'})});
  await api('/api/portfolio/CASH_KRW', {method:'PUT', headers:{'Content-Type':'application/json','X-Portfolio-Account':initial}, body:JSON.stringify({quantity:1000000,avg_price:1,stock_name:'원화'})});
  await page.reload();
  await expect(page.locator('#pfBody tr[data-code="005930"]')).toBeVisible();
  await page.locator('#pfAccountsOpen').click();
  await page.locator('#pfAccountName').fill('분산 계좌');
  await page.locator('#pfAccountCreate').click();
  await expect(page.locator('#pfAccountsStatus')).toContainText('계좌를 만들었습니다');
  const second = (await api('/api/portfolio/accounts')).body.find(row => row.name === '분산 계좌').account_id;
  await page.locator(`#pfAccountsList [data-account="${second}"] [data-account-action="view"]`).click();
  await expect(page.locator('#pfAccountSelect')).toHaveValue(second);
  await expect(page.locator('#pfBody tr[data-code="005930"]')).not.toBeVisible();
  await page.locator('#pfAddToggle').click();
  await page.locator('input[name="pfAddMode"][value="holding"]').check();
  await page.locator('#pfAddInput').fill('005930');
  await page.locator('#pfAddBtn').click();
  await page.locator('#pfRegisterQuantity').fill('5');
  await page.locator('#pfRegisterPrice').fill('80000');
  await page.locator('#pfRegisterSave').click();
  await expect(page.locator('#pfRegisterDialog')).not.toBeVisible();
  const scoped = (await api('/api/portfolio?account_id='+second)).body;
  expect(scoped.find(row => row.stock_code === '005930').quantity).toBe(5);
  expect(scoped.some(row => row.stock_code === 'CASH_KRW')).toBe(false);
  await page.locator('#pfBody tr[data-code="005930"] .js-pf-trade').click();
  await page.locator('#pfTradeQuantity').fill('1');
  await page.locator('#pfTradePrice').fill('100');
  await page.locator('#pfTradePreviewButton').click();
  await expect(page.locator('#pfTradeStatus')).toContainText('현금이 부족');
  await page.locator('#pfTradeSide').selectOption('sell');
  await page.locator('#pfTradePreviewButton').click();
  await expect(page.locator('#pfTradeSave')).toBeEnabled();
  await page.locator('#pfTradeSave').click();
  await expect(page.locator('#pfTradeStatus')).toContainText('저장했습니다');
  await page.locator('#pfTradeClose').click();
  expect((await api('/api/portfolio?account_id='+initial)).body.find(row => row.stock_code === 'CASH_KRW').quantity).toBe(1000000);
  await page.locator('#pfAccountSelect').selectOption('');
  await expect(page.locator('#pfBody tr[data-code="005930"] .js-pf-account-detail')).toBeVisible();
  expect((await api('/api/portfolio')).body.find(row => row.stock_code === '005930').quantity).toBe(14);
  await page.locator('#pfAccountsOpen').click();
  await page.locator('#pfAccountName').fill('NH 연결');
  await page.locator('#pfAccountCreate').click();
  await expect(page.locator('#pfAccountsStatus')).toContainText('계좌를 만들었습니다');
  const nh = (await api('/api/portfolio/accounts')).body.find(row => row.name === 'NH 연결').account_id;
  const card = page.locator(`#pfAccountsList [data-account="${nh}"]`);
  await card.locator('[data-account-action="connect"]').click();
  await page.locator('#pfNhKey').fill('browser-namuh-key');
  await page.locator('#pfNhSecret').fill('browser-namuh-secret');
  await page.locator('#pfNhForm button[type="submit"]').click();
  await expect(page.locator('#pfNhChoices')).toContainText('8901');
  await expect(page.locator('#pfNhKey')).toHaveValue('');
  await page.locator('#pfNhPreviewButton').click();
  await expect(page.locator('#pfNhPreview')).toContainText('삼성전자');
  await page.locator('#pfNhDialog').screenshot({path:testInfo.outputPath('nh-preview.png')});
  await page.locator('#pfNhClose').click();
  expect((await api('/api/portfolio?account_id='+nh)).body).toEqual([]);
  await card.locator('[data-account-action="connect"]').click();
  await page.locator('#pfNhKey').fill('browser-namuh-key');
  await page.locator('#pfNhSecret').fill('browser-namuh-secret');
  await page.locator('#pfNhForm button[type="submit"]').click();
  await expect(page.locator('#pfNhPreviewButton')).toBeEnabled();
  await page.locator('#pfNhPreviewButton').click();
  await expect(page.locator('#pfNhSave')).toBeEnabled();
  await page.locator('#pfNhSave').click();
  await expect(page.locator('#pfNhDialog')).not.toBeVisible();
  await expect(card).toContainText('NH');
  expect((await api('/api/portfolio')).body.find(row => row.stock_code === '005930').quantity).toBe(17);
  const denied = await api('/api/portfolio/005930', {method:'PUT', headers:{'Content-Type':'application/json','X-Portfolio-Account':nh}, body:JSON.stringify({quantity:1,avg_price:1})});
  expect(denied.status).toBe(400);
  await page.setViewportSize({width:390,height:844});
  expect(await page.locator('#pfAccountsDialog').evaluate(el => el.scrollWidth > el.clientWidth)).toBe(false);
  await page.locator('#pfAccountsDialog').screenshot({path:testInfo.outputPath('accounts-mobile.png')});
});
