import { test, expect } from '@playwright/test';

test('연동 종목의 설정 편집·위치 이동은 허용하고 잔고는 보호하며 동기화 뒤에도 설정을 유지한다', async ({page}, testInfo) => {
  test.setTimeout(90_000);
  page.setDefaultTimeout(10_000);
  await page.routeWebSocket('**/ws/broker-accounts', () => {});
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.goto('/login');
  const headers = {Origin: 'http://127.0.0.1:18765'};
  const signup = await page.request.post('/api/auth/register', {headers, data: {
    email: `metadata-${Date.now()}@example.com`, name: '설정 검증', password: 'browser-test-password',
  }});
  expect(signup.ok()).toBe(true);
  await page.goto('/portfolio');
  await expect(page.locator('#pfAccountSelect option')).toHaveCount(2);
  const accounts = await (await page.request.get('/api/portfolio/accounts')).json();
  const manual = accounts[0].account_id;
  await page.request.put('/api/portfolio/000660', {headers: {...headers, 'X-Portfolio-Account': manual},
    data: {stock_name: 'SK하이닉스', quantity: 2, avg_price: 100000}});
  await page.locator('#pfAccountsOpen').click();
  await page.locator('#pfAccountName').fill('NH 설정 검증');
  await page.locator('#pfAccountCreate').click();
  const card = page.locator('#pfAccountsList .pf-account-card').filter({has: page.locator('h3', {hasText: 'NH 설정 검증'})});
  await expect(card).toBeVisible();
  const aid = await card.getAttribute('data-account');
  await card.locator('[data-account-action="connect"]').click();
  await page.locator('#pfNhKey').fill('metadata-'+Date.now());
  await page.locator('#pfNhSecret').fill('metadata-test-secret');
  await page.locator('#pfNhVerify').click();
  await expect(page.locator('#pfNhPreviewButton')).toBeEnabled();
  await page.locator('#pfNhPreviewButton').click();
  await expect(page.locator('#pfNhSave')).toBeEnabled();
  await page.locator('#pfNhSave').click();
  await expect(page.locator('#pfNhDialog')).not.toBeVisible();
  await card.locator('[data-account-action="view"]').click();
  await expect(page.locator('#pfAccountSelect')).toHaveValue(aid);
  await expect.poll(() => page.locator('#pfBody tr').evaluateAll(rows => rows.map(row => row.dataset.code)))
    .toEqual(['005930', 'CASH_KRW']);
  const row = page.locator('#pfBody tr[data-code="005930"]');
  await expect(row.locator('.js-pf-edit')).toBeVisible();
  await expect(row.locator('.js-pf-delete,.js-pf-trade')).toHaveCount(0);
  for (const key of ['target', 'date', 'memo']) await page.locator(`.js-pf-col-toggle[data-col-key="${key}"]`).check();
  await row.locator('.js-pf-edit').click();
  await expect(page.locator('#pfAccountsDialog')).not.toBeVisible();
  await expect(page.locator('#pfEditQty')).toBeDisabled();
  await expect(page.locator('#pfEditPrice')).toBeDisabled();
  await row.locator('.js-pf-bench-picker').click();
  await row.locator('[data-bench="IDX_SP500"]').click();
  await expect(row.locator('.pf-benchmark-name')).toContainText('S&P50');
  const groups = await row.locator('.js-pf-group option').evaluateAll(options => options.map(x => x.value));
  const group = groups.at(-1);
  const groupSaved = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/005930/group'));
  await row.locator('.js-pf-group').selectOption(group);
  expect((await groupSaved).ok()).toBe(true);
  await page.locator('#pfEditName').fill('내 삼성전자');
  await page.locator('#pfEditTarget').fill('120000');
  await page.locator('#pfEditMemo').fill('장기 보유 메모');
  await page.locator('#pfEditCreatedAt').fill('2020-02-20');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({path: testInfo.outputPath('linked-metadata-edit.png'), fullPage:true});
  const saved = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/005930/metadata'));
  await row.locator('.js-pf-save').click();
  const response = await saved;
  expect(response.ok()).toBe(true);
  expect(response.request().postDataJSON()).not.toHaveProperty('quantity');
  expect(response.request().postDataJSON()).not.toHaveProperty('avg_price');
  await expect(row.locator('.pf-stock-link')).toHaveText('내 삼성전자');
  await expect(row.locator('.pf-col-qty')).toHaveText('3');
  await expect(row.locator('.pf-col-buyprice')).toContainText('80,000');

  const orderBefore = (await (await page.request.get('/api/portfolio')).json()).map(x => x.stock_code);
  const from = page.locator('#pfBody tr').last();
  const to = page.locator('#pfBody tr').first();
  const fromCode = await from.getAttribute('data-code');
  const toCode = await to.getAttribute('data-code');
  const reordered = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/portfolio/order'));
  await from.locator('.js-pf-row-drag').dragTo(to.locator('.js-pf-row-drag'), {targetPosition: {x: 12, y: 2}});
  expect((await reordered).ok()).toBe(true);
  await expect(page.locator('#pfBody tr').first()).toHaveAttribute('data-code', fromCode);
  const orderAfter = (await (await page.request.get('/api/portfolio')).json()).map(x => x.stock_code);
  expect(orderAfter).toEqual(orderBefore);
  await page.locator('#pfAccountsOpen').click();
  await card.locator('[data-account-action="sync"]').click();
  await expect(page.locator('#pfAccountsStatus')).toContainText('반영했습니다');
  await page.locator('#pfAccountsClose').click();
  await page.reload();
  await page.locator('#pfAccountSelect').selectOption(aid);
  await expect(row.locator('.pf-stock-link')).toHaveText('내 삼성전자');
  const snapshot = (await (await page.request.get('/api/portfolio?account_id='+aid)).json()).find(x => x.stock_code === '005930');
  expect(snapshot).toMatchObject({stock_name:'내 삼성전자', quantity:3, avg_price:80000,
    target_price:120000, memo:'장기 보유 메모', benchmark_code:'IDX_SP500', group_name:group, created_at:'2020-02-20T00:00:00'});
  expect((await (await page.request.get('/api/portfolio?account_id='+aid)).json()).map(x => x.stock_code)).toEqual([fromCode, toCode]);
  // 합산 보기에서도 공통 설정을 편집할 수 있다.
  await page.locator('#pfAccountSelect').selectOption('');
  await row.locator('.js-pf-edit').click();
  await expect(page.locator('#pfEditQty')).toBeDisabled();
  const cleared = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/005930/metadata'));
  await row.locator('.js-pf-target-clear').click();
  expect((await cleared).ok()).toBe(true);
  await row.locator('.js-pf-cancel').click();
  await expect(row.locator('.pf-col-target')).toHaveText('-');
  await page.locator('#pfCompactToggle').check();
  await expect(row.locator('.js-pf-edit')).not.toBeVisible();
  await expect(row.locator('.js-pf-row-drag')).toBeVisible();
  const compactFrom = page.locator('#pfBody tr').last();
  const compactTo = page.locator('#pfBody tr').first();
  const compactFromCode = await compactFrom.getAttribute('data-code');
  const compactOrderSaved = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/portfolio/order'));
  await compactFrom.locator('.js-pf-row-drag').dragTo(compactTo.locator('.js-pf-row-drag'), {targetPosition: {x: 12, y: 2}});
  expect((await compactOrderSaved).ok()).toBe(true);
  await expect(page.locator('#pfBody tr').first()).toHaveAttribute('data-code', compactFromCode);
  await page.evaluate(() => {window.scrollTo(0,0); document.querySelector('#pfHoldingsTab .pf-table-wrap').scrollLeft=0;});
  await page.screenshot({path:testInfo.outputPath('linked-compact-drag.png'),fullPage:true});
  await page.locator('#pfCompactToggle').uncheck();
  await expect(row.locator('.js-pf-edit')).toBeVisible();
});
