import { test, expect } from '@playwright/test';

test('매매 기록의 현금 선택으로 양방향 환전을 저장하고 모바일과 새로고침에서도 잔고를 유지한다', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.goto('/login?return_to=/portfolio');
  await page.locator('#loginEmail').fill('browser@example.com');
  await page.locator('#loginPassword').fill('browser-test-password');
  await page.getByRole('button', { name: '이메일로 로그인' }).click();
  await expect(page.locator('#pfBody tr[data-code="CASH_KRW"]')).toBeVisible();
  const balances = () => page.evaluate(async () => (await (await fetch('/api/portfolio')).json()).filter(row => row.stock_code.startsWith('CASH_')));
  const before = await balances();
  const krw = before.find(row => row.stock_code === 'CASH_KRW').quantity;
  const usd = before.find(row => row.stock_code === 'CASH_USD')?.quantity || 0;
  const cashflows = await page.evaluate(async () => (await fetch('/api/portfolio/cashflows')).json());
  await page.locator('#pfBody tr[data-code="CASH_KRW"]').getByRole('button', { name: '환전', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '매매 기록', exact: true });
  await expect(page.locator('#pfTradeOrderFields')).toBeHidden();
  await expect(page.locator('#pfTradeExchangeFrom')).toHaveValue('KRW');
  await expect(page.locator('#pfTradeExchangeTo')).toHaveValue('USD');
  await page.locator('#pfTradeExchangeAmount').fill('140000');
  await page.locator('#pfTradeExchangeRate').fill('1400');
  await page.locator('#pfTradeExchangeFees').fill('1000');
  await expect(page.locator('#pfTradeExchangeEstimate')).toContainText('차감 141,000 KRW → 수령 100 USD');
  await dialog.screenshot({ path: testInfo.outputPath('exchange-desktop.png') });
  await page.getByRole('button', { name: '변경 내용 확인' }).click();
  await expect(page.locator('#pfTradePreview')).toContainText('KRW → USD 환전');
  await page.getByRole('button', { name: '환전 기록 저장' }).click();
  await expect(page.locator('#pfTradeStatus')).toContainText('두 통화의 현금 잔고를 저장했습니다');
  const bought = await balances();
  expect(bought.find(row => row.stock_code === 'CASH_KRW').quantity).toBe(krw - 141000);
  expect(bought.find(row => row.stock_code === 'CASH_USD').quantity).toBe(usd + 100);
  await page.getByRole('button', { name: '매매 기록 닫기' }).click();
  await page.reload();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '매매 기록', exact: true }).click();
  await page.locator('#pfTradeStock').fill('CASH_USD');
  await expect(page.locator('#pfTradeExchangeFrom')).toHaveValue('USD');
  await expect(page.locator('#pfTradeExchangeTo')).toHaveValue('KRW');
  await page.locator('#pfTradeExchangeAmount').fill('100');
  await page.locator('#pfTradeExchangeRate').fill('1400');
  await expect(page.locator('#pfTradeExchangeEstimate')).toContainText('수령 140,000 KRW');
  expect(await dialog.evaluate(el => el.scrollWidth > el.clientWidth)).toBe(false);
  await dialog.screenshot({ path: testInfo.outputPath('exchange-mobile.png') });
  await page.getByRole('button', { name: '변경 내용 확인' }).click();
  await page.getByRole('button', { name: '환전 기록 저장' }).click();
  await expect(page.locator('#pfTradeStatus')).toContainText('저장했습니다');
  await dialog.locator('.pf-trade-history summary').click();
  await expect(page.locator('#pfTradeHistory article').first()).toContainText('USD → KRW · 환전');
  await page.getByRole('button', { name: '매매 기록 닫기' }).click();
  await page.reload();
  const after = await balances();
  expect(after.find(row => row.stock_code === 'CASH_KRW').quantity).toBe(krw - 1000);
  expect(after.find(row => row.stock_code === 'CASH_USD').quantity).toBe(usd);
  expect(await page.evaluate(async () => (await fetch('/api/portfolio/cashflows')).json())).toEqual(cashflows);
  expect(errors).toEqual([]);
});
