import { test, expect } from '@playwright/test';

test('매매 기록에서 미리보기·매수·매도 후 현금과 보유 수량이 새로고침에도 유지된다', async ({ page }, testInfo) => {
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.goto('/login?return_to=/portfolio');
  await page.locator('#loginEmail').fill('browser@example.com');
  await page.locator('#loginPassword').fill('browser-test-password');
  await page.getByRole('button', { name: '이메일로 로그인' }).click();
  await expect(page.locator('#pfBody tr[data-code="005930"]')).toBeVisible();
  const before = await page.evaluate(async () => (await fetch('/api/portfolio')).json());
  const stockBefore = before.find(i => i.stock_code === '005930');
  const cashBefore = before.find(i => i.stock_code === 'CASH_KRW');
  await page.locator('#pfBody tr[data-code="005930"] .js-pf-trade').click();
  const dialog = page.getByRole('dialog', { name: '매매 기록' });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel('수량', { exact: true }).fill('2');
  await page.getByLabel('체결 단가', { exact: true }).fill('80000');
  await page.locator('#pfTradeFees').fill('100');
  await page.getByRole('button', { name: '변경 내용 확인' }).click();
  await expect(page.locator('#pfTradePreview')).toContainText('160,000 / 100 KRW');
  await dialog.screenshot({ path: testInfo.outputPath('trade-desktop.png') });
  await page.getByRole('button', { name: '매매 기록 저장' }).click();
  await expect(page.locator('#pfTradeStatus')).toContainText('저장했습니다');
  await page.getByRole('button', { name: '매매 기록 닫기' }).click();
  await page.reload();
  const bought = await page.evaluate(async () => (await fetch('/api/portfolio')).json());
  expect(bought.find(i => i.stock_code === '005930').quantity).toBe(stockBefore.quantity + 2);
  expect(bought.find(i => i.stock_code === 'CASH_KRW').quantity).toBe(cashBefore.quantity - 160100);

  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.locator('.pf-tab-bar').evaluate(el => el.scrollWidth > el.clientWidth)).toBe(false);
  await page.getByRole('button', { name: '매매 기록', exact: true }).click();
  await page.locator('#pfTradeStock').fill('삼성전자 (005930)');
  await page.locator('#pfTradeSide').selectOption('sell');
  await page.locator('#pfTradeQuantity').fill('1');
  await page.locator('#pfTradePrice').fill('85000');
  await page.locator('#pfTradeFees').fill('50');
  await page.getByRole('button', { name: '변경 내용 확인' }).click();
  await expect(page.locator('#pfTradePreview')).toContainText('삼성전자 매도');
  const overflow = await dialog.evaluate(el => el.scrollWidth > el.clientWidth);
  expect(overflow).toBe(false);
  await dialog.screenshot({ path: testInfo.outputPath('trade-mobile.png') });
  await page.getByRole('button', { name: '매매 기록 저장' }).click();
  await expect(page.locator('#pfTradeStatus')).toContainText('저장했습니다');
  await page.locator('.pf-trade-history summary').click();
  await expect(page.locator('#pfTradeHistory article').first()).toContainText('매도');
  const sold = await page.evaluate(async () => (await fetch('/api/portfolio')).json());
  expect(sold.find(i => i.stock_code === '005930').quantity).toBe(stockBefore.quantity + 1);
  expect(sold.find(i => i.stock_code === 'CASH_KRW').quantity).toBe(cashBefore.quantity - 160100 + 84950);
});
